name: 'Closed Issue Comment'
on:
  issue_comment:
    types:
      - created
jobs:
  closed-issue-comment:
    # skip in fork
    if: github.repository == 'cypress-io/cypress-example-todomvc'
    uses: cypress-io/cypress/.github/workflows/triage_closed_issue_comment.yml@develop
    secrets: inherit
